# Generated by Django 2.2 on 2019-04-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currency_USD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('cost', models.FloatField()),
                ('pub_date', models.DateTimeField(verbose_name='last update')),
            ],
        ),
        migrations.CreateModel(
            name='currency_Pln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('cost', models.FloatField()),
                ('pub_date', models.DateTimeField(verbose_name='last update')),
                ('usd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency_USD')),
            ],
        ),
        migrations.CreateModel(
            name='currency_Euro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('cost', models.FloatField()),
                ('pub_date', models.DateTimeField(verbose_name='last update')),
                ('usd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency_USD')),
            ],
        ),
        migrations.CreateModel(
            name='currency_Czk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('cost', models.FloatField()),
                ('pub_date', models.DateTimeField(verbose_name='last update')),
                ('usd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency_USD')),
            ],
        ),
    ]
