# Generated by Django 2.2 on 2019-04-02 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20190402_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_czk',
            name='usd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency_USD'),
        ),
        migrations.AlterField(
            model_name='currency_euro',
            name='usd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency_USD'),
        ),
        migrations.AlterField(
            model_name='currency_pln',
            name='usd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency_USD'),
        ),
    ]
