# Generated by Django 2.2 on 2019-04-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20190402_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_czk',
            name='usd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency_USD'),
        ),
        migrations.AlterField(
            model_name='currency_euro',
            name='usd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency_USD'),
        ),
        migrations.AlterField(
            model_name='currency_pln',
            name='usd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.Currency_USD'),
        ),
        migrations.AlterField(
            model_name='currency_usd',
            name='pub_date',
            field=models.DateField(verbose_name='last update'),
        ),
    ]
