# Generated by Django 2.2 on 2019-04-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_auto_20190402_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='czk_name',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='euro_name',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='pln_name',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='usd_name',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
